language: objective-c
osx_image: xcode9.1
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphoneos11.1
script:
  - xcodebuild -showsdks
  - xcodebuild -project Blurry.xcodeproj -scheme 'Debug' -sdk $IOS_SDK build analyze
